spring.application.name=threat-api-service
# Run this service on Port 8083
server.port=8083

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/threat_intel_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update