spring.application.name=extraction-service
# Run this service on a different port
server.port=8082

# Tell it where Kafka is
spring.kafka.consumer.bootstrap-servers=localhost:9092

# Give this consumer a name (required by Kafka)
spring.kafka.consumer.group-id=extraction-group

# Tell it to read all messages from the beginning if it missed any
spring.kafka.consumer.auto-offset-reset=earliest

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/threat_intel_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update