spring.application.name=ingestion-service
spring.kafka.producer.bootstrap-servers=localhost:9092
server.port=8080

# Existing AbuseIPDB Key
abuseipdb.api.key=deda159f1b9744e1a07a9959a8c3130da0aaa3310d9f0dab395970273623b26f73efd34cf4a549cf

# New AlienVault OTX Key
alienvault.api.key=07e8a54dd0870515da3c9ddc2df80009f48c3d6d117e3fb490684768ef018558
alienvault.api.url=https://otx.alienvault.com/api/v1/pulses/subscribed